### PR TITLE
Update ember and deps

### PR DESCRIPTION
**Pull request by rwwagner90**
I noticed some deps were out of date, especially ember-cli-babel, so I went ahead and took a stab at updating most things. Let me know if you would like me to tweak anything!

### CODE REVIEW

**Comment by mitchlloyd** [comment]
Yeah an ember-cli and dependency update is a little over due here. Thanks!

A couple things:

1. Could we also add ember-lts-2.4 to the Ember try scenarios? Some parts of this addon are coupled to Ember internals that change between versions so it's nice to have a little more coverage. 
2. I'm getting pwned by this ember-try issue running things locally with npm >= 5. Maybe we could wait for this to land and give it a shot? https://github.com/ember-cli/ember-try/pull/151.

**Comment by rwwagner90** [comment]
Hi @mitchlloyd! I added the 2.4 LTS, but it looks like Travis isn't turned on? There are no tests running on this PR here. Can we enable Travis please?

What is happening with ember-try? I've got all my addons using it, and on later Node versions with no problem.

**Comment by mitchlloyd** [comment]
I still can't run the full test suite locally without downgrading npm, but having everything running on travis seems more important.

Thanks for the help and the persistence!

**Comment by rwwagner90** [comment]
@mitchlloyd I never really run ember-try locally, I just use it for travis. I wouldn't worry about npm 5.

**Comment by nudded** [comment]
@mitchlloyd any chance you could push an update to npm registry?

**Comment by nudded** [comment]
@mitchlloyd Thanks!

**Pull request merged**
