### PR TITLE
Save the component instance on the parent element

### PR DESCRIPTION
**Pull request by himynameisjonas**
I'm not sure if this is something that should exist in this package or if it's the best way to do it.
However, I wanted a easy way to access the instantiated components from my old app (rails + jquery) to be able to destroy the components so I can render new once.

So basically I have an initializer in my ember app:
```js
import renderComponents from 'ember-islands/render-components';

export function initialize(container, application) {
  window.renderComponents = function(){
    renderComponents(application);
  };

  window.destroyComponents = function(){
    $('[data-component]').each(function(){
      $(this).data('component-instance').destroy();
    });
  };
}
```

And then I have a list with components that get replaced with old school ajax:
```js
window.destroyComponents();
$("#wrapper").html(data.html);
window.renderComponents();
```

Maybe this could be helpful for someone, even if it's not merged.

Thanks again for the work on ember-island!

### CODE REVIEW

**Comment by mitchlloyd** [comment]
@himynameisjonas I feel like I can't quite grok what the use case is here. I see that you're destroying all of the components and rendering them again, but I'm not sure what's going on in between or why it's happening?

Can you tell me a little more about the use case?

**Comment by himynameisjonas** [comment]
Our old rails app renders a list that we're slowly converting to ember. So that list contains a lot of `<div data-component="…` and it works really well until that list is changed by our old js: It removes the content and replaces it with new html from the server (with ajax). So my app-specific initializer that assigns `window.renderComponents` makes it possible to instantiate the new components after the ajax replacement.

But some of the component divs returned in the axaj request might be the same as before and i got some conflicts when ember already had a component with the same data and ids. So that's why i need to run `destroyComponents` before our old js replaces the list of components.

I'm not sure if I make any sense at all :)

**Comment by mitchlloyd** [comment]
That does make sense. The whole idea of this library is to bridge the gap between legacy server + client rendering and Ember so on the face of it this feature looks good. However, I'm wondering if it might be better to lean a little more on Ember in this case.

Would it work to use the `init()` hook to stash your components when they are created?

```javascript
export default Ember.Component.extend({
  init() {
    this._super(...arguments);
    window.componentList.push(this);
  }

  willDestroy() {
    _.remove(window.componentList, (c) => c === this);
  }
});
```

And if you did want to stash the instance on the element:

```javascript
export default Ember.Component.extend({
  didInsertElement() {
    this.$().data('component-instance', this);
  }

  willDestroyElement() {
    this.$().data('component-instance', null);
  }
});
```

**Comment by himynameisjonas** [comment]
Yeah, that looks much better, Thanks!

**Pull request closed without merging**
