### PR TITLE
Ember 1.13 compatibility (fixes #8)

### LINKED ISSUE #8: Initalizer error in 2.0.0-canary+e6517064
Trying to run Ember with ember-islands in canary is throwing the following error:
```
Uncaught Error: Assertion Failed: No application initializer named 'registerComponentLookup'
_emberMetalCore.default.assert	@	ember.debug.js:5320
(anonymous function)	@	ember.debug.js:4323
(anonymous function)	@	ember.debug.js:4348
visit	@	ember.debug.js:2238
visit	@	ember.debug.js:2236
DAG.topsort	@	ember.debug.js:2349
_emberRuntimeSystemNamespace.default.extend._runInitializer	@	ember.debug.js:4347
_emberRuntimeSystemNamespace.default.extend.runInitializers	@	ember.debug.js:4322
_emberRuntimeSystemNamespace.default.extend.boot	@	ember.debug.js:4239
_emberRuntimeSystemNamespace.default.extend.domReady	@	ember.debug.js:4225
Backburner.run	@	ember.debug.js:222
Backburner.join	@	ember.debug.js:261
run.join	@	ember.debug.js:19537
run.bind	@	ember.debug.js:19600
jQuery.Callbacks.fire	@	base.js:3124
jQuery.Callbacks.self.fireWith	@	base.js:3236
jQuery.extend.ready	@	base.js:3448
completed	@	base.js:3479
```

Seems to be related to `registerComponentLookup` changing from an `initializer` [in 1.13](https://github.com/emberjs/ember.js/blob/v1.13.0-beta.2/packages/ember-htmlbars/lib/system/bootstrap.js#L98) to an `instanceInitializer` [in canary](https://github.com/emberjs/ember.js/blob/4d97d612ebe0841c0d40e57b276c9bc2bf896768/packages/ember-htmlbars/lib/system/bootstrap.js#L98).

### PR DESCRIPTION
**Pull request by praxxis**
The `registerComponentLookup` initializer is now an instance initializer, so we need to change the ember-islands boot initializer to an instance initializer too. Unfortunately there's no clean way to plumb the `bypass` config flag through to the instance, as instances do not have access to the parent application. To get around this we just set the config flag directly on the default/deprecated instance that exists in 1.13.

Note that these changes mean that ember-islands will only work in Ember 1.13+.

This was the simplest set of changes that got ember-islands working with 1.13, and setting `bypass` on the deprecated instance feels pretty hacky. In the future I could see us moving toward having some sort of "config" object in the application registry, that each instance could query for the `bypass` flag.

### CODE REVIEW

**Comment by mitchlloyd** [comment]
Thanks so much for putting this together!  I'm traveling right now but I should be able to review and merge Sunday.

**Comment by praxxis** [comment]
np! It's also likely that this is just a stopgap fix, until https://github.com/emberjs/ember.js/pull/11440 is merged

**Comment by mitchlloyd** [comment]
This looks good but I just ran with ember-try and got a failure in Canary.  For some reason it can't load the files from the `addon` directory. Really weird because it works with 1.12. 

Chasing Canary is tough, I'm looking forward to having that container PR merged!

**Comment by hhff** [comment]
@mitchlloyd - I'm seeing that same `/addon` directory thing with my Ember Infinity addon against canary.  going to do a sprint on it tonight but if you have any insight I'd love to hear it!

**Comment by praxxis** [comment]
So the failure is apparently related to [Ember Data not working in canary](https://github.com/stefanpenner/ember-moment/issues/38#issuecomment-88223300), which kills the rest of the build. Removing ED from package.json and bower.json fixes the failure. cc @hhff 

That being said, would we be able to get this merged as 0.6.0 (or a version of your choosing)? I'll come back and do a second pass once the container reform is done, which'll hopefully mean we can remove some of the hackier code.

**Comment by mitchlloyd** [comment]
@praxxis This seems like a bug fix (no new features) so I was thinking about just a patch number bump. I'll remove Ember Data from `bower.json`. 

I really wish all of the recent 1.x releases would just work and then we could break for 2.0. I'll look into adding more hacks to detect this particular case so that it can work with 1.13 and 1.12.

**Comment by praxxis** [comment]
Something using https://github.com/rwjblue/ember-cli-version-checker#real-world-example might be a solution?

**Comment by mitchlloyd** [comment]
That's interesting. It seems like our own ad hoc feature detection here would probably not work since this is happening during Ember's boot process?

@praxxis If you have the time would you mind putting something together? I'm moving this week and I'm really pressed for time.

**Comment by praxxis** [comment]
Sure thing

**Comment by praxxis** [comment]
So a major problem is that the `after` property of the initializer and instance initializer is invalid/invalid when you switch versions (it's `after` `registerComponentLookup` in the 1.12 initializer, changing to the instance initializer in 1.13.) And booting fails hard if either `after` is invalid. And there's no way to feature detect for that, as the initializers need to be loaded to even see which ones are present. 

I'm going to play around with trying to change the initializer behaviour based on `Ember.VERSION` but that feels really hacky :(

**Comment by praxxis** [comment]
@mitchlloyd ok, this is what I ended up with. We basically ship pre- and post-fastboot initializers now. The code is duplicated but it seems clearer than trying to add in version logic, and the real work is done outside of the initializers anyway.

**Comment by hhff** [comment]
word thanks @praxxis

**Comment by mitchlloyd** [comment]
@praxxis This looks really great. Thanks for helping out with this!

**Comment by hhff** [comment]
Yo @praxxis / @mitchlloyd - just put together an addon that might help here: https://github.com/hhff/ember-version-is

**Pull request merged**
